name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Authenticate to Docker Hardened Image Registry
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/josephyi/docker-dhi-example
      - uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          buildkitd-config-inline: |
            [registry."dhi.io"]
              mirrors = ["dhi.io"]
      - name: build manually
        run: |
          docker buildx inspect
          docker run --rm dhi.io/python:3.13 python -c "print('Hello from DHI')"
      - name: Build with buildx directly
        run: |
          docker buildx build \
            --tag ghcr.io/josephyi/docker-dhi-example:test \
            --load \
            .
      - name: Build and Load Image
        id: build-pr
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          load: true
          push: false

